### ISSUE TITLE
Errors under Windows

### ISSUE THREAD

**Issue by dlilienthal** [schlarpc/SeriousCast#10]
This program was working as of 10-11-2015.  When I ran server.py today, the following messages appeared:

INFO :: 3576  :: Setting up server, please wait
Traceback (most recent call last):
  File "C:\Users\DaveL\Dev\SiriusXM\3rd Party\SeriousCast\server.py", line 273, in <module> 
    sbe = SeriousBackend()
  File "C:\Users\DaveL\Dev\SiriusXM\3rd Party\SeriousCast\server.py", line 26, in **call**
    cls._instances[cls] = super(Singleton, cls).__call__(_args, *_kwargs)
  File "C:\Users\DaveL\Dev\SiriusXM\3rd Party\SeriousCast\server.py", line 39, in **init**
    self.sxm = sirius.Sirius()
  File "C:\Users\DaveL\Dev\SiriusXM\3rd Party\SeriousCast\sirius.py", line 104, in **init**
    config_url = re.search("flashvars.configURL = '(.+?)'", player_page).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

I am using Python 3.5.0 + requirements as follows:
"Successfully installed Jinja2-2.8 MarkupSafe-0.23 bitstring-3.1.3 cffi-1.3.1 cry
ptography-1.1.1 idna-2.0 pyasn1-0.1.9 pycparser-2.14 requests-2.8.1 six-1.10.0"

The same errors appear under Windows 10 x64 and Windows 7 x64.

**Comment by LoraCadi** [comment]
https://www.siriusxm.com/legacyplayer/ no longer available - needs updating
