### ISSUE TITLE
SiriusXM changed his webplayer to html5

### ISSUE THREAD

**Issue by jz1** [schlarpc/SeriousCast#6]
broken for now, new player: https://player.siriusxm.com/vendor/sxm-audioplayer/web-audio-player.js
Traceback (most recent call last):
  File "streamdl.py", line 15, in <module>
    sxm = sirius.Sirius()
  File "D:\Recorded Media\SiriusXM\SeriousCast-master\sirius.py", line 104, in _
_init__
    config_url = re.search("flashvars.configURL = '(.+?)'", player_page).group(1
)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by schlarpc** [comment]
Thanks for the heads up, I'll look into it when I get a chance.

**Comment by jz1** [comment]
i dont think they changed the decryption part thought, since i found that aes key in one of the m3u8 files to. Althought i try to read your code in reverse to see how u decrypting it. But i'm struggling with that. Python is not my best language.

**Comment by schlarpc** [comment]
I merged your pull request in 41d1e6f6. That should work for now, at least until the code can be ported to the new backend.

**Comment by andrew0** [comment]
The AES key hasn't changed - it's the same one in sirius.py. It's sent through a json request, but it's the same for every channel.

**Comment by jz1** [comment]
Andrew0 good work on it! saw your script on page, althouht i wish it could be implented in this script.

**Comment by clinton05** [comment]
looks like it's down now? no response from production-authentication.siriusxm.com
